# Generated by Django 4.2.23 on 2025-08-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_expire_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_stock', 'can_update_stock')]},
        ),
    ]
