# Generated by Django 4.2.23 on 2025-08-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_stock', 'can view stock'), ('can_update_stock', 'can_update_stock')]},
        ),
    ]
